/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConsoleRouteRouteImport } from './routes/console/route'
import { Route as EndShiftRouteImport } from './routes/end-shift'
import { Route as ReportRouteImport } from './routes/report'
import { Route as TimelineRouteImport } from './routes/timeline'
import { Route as ConsoleIndexRouteImport } from './routes/console/index'
import { Route as ConsoleAdminRouteRouteImport } from './routes/console/admin/route'
import { Route as ConsoleCalendarRouteImport } from './routes/console/calendar'
import { Route as ConsoleDataRouteImport } from './routes/console/data'
import { Route as ConsoleEventsRouteImport } from './routes/console/events'
import { Route as ConsoleIntegrationsRouteImport } from './routes/console/integrations'
import { Route as ConsoleMaintenanceRouteImport } from './routes/console/maintenance'
import { Route as ConsoleRcaRouteImport } from './routes/console/rca'
import { Route as ConsoleShiftsRouteImport } from './routes/console/shifts'
import { Route as ConsoleTeamsRouteImport } from './routes/console/teams'
import { Route as InviteTokenRouteImport } from './routes/invite/$token'
import { Route as ConsoleAdminIndexRouteImport } from './routes/console/admin/index'
import { Route as ConsoleAdminTenantIdRouteImport } from './routes/console/admin/$tenantId'
import { Route as ConsoleAdminTenantIdIndexRouteImport } from './routes/console/admin/$tenantId/index'
import { Route as ConsoleAdminTenantIdInviteRouteImport } from './routes/console/admin/$tenantId/invite'
import { Route as ConsoleAdminTenantIdOnboardRouteImport } from './routes/console/admin/$tenantId/onboard'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleRouteRoute = ConsoleRouteRouteImport.update({
  id: '/console',
  path: '/console',
  getParentRoute: () => rootRouteImport,
} as any)
const EndShiftRoute = EndShiftRouteImport.update({
  id: '/end-shift',
  path: '/end-shift',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const TimelineRoute = TimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleIndexRoute = ConsoleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ConsoleRouteRoute,
} as any)
const ConsoleAdminRouteRoute = ConsoleAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => ConsoleRouteRoute,
} as any)
const ConsoleCalendarRoute = ConsoleCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => ConsoleRouteRoute,
} as any)
const ConsoleDataRoute = ConsoleDataRouteImport.update({
  id: '/data',
  path: '/data',
  getParentRoute: () => ConsoleRouteRoute,
} as any)
const ConsoleEventsRoute = ConsoleEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => ConsoleRouteRoute,
} as any)
const ConsoleIntegrationsRoute = ConsoleIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => ConsoleRouteRoute,
} as any)
const ConsoleMaintenanceRoute = ConsoleMaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => ConsoleRouteRoute,
} as any)
const ConsoleRcaRoute = ConsoleRcaRouteImport.update({
  id: '/rca',
  path: '/rca',
  getParentRoute: () => ConsoleRouteRoute,
} as any)
const ConsoleShiftsRoute = ConsoleShiftsRouteImport.update({
  id: '/shifts',
  path: '/shifts',
  getParentRoute: () => ConsoleRouteRoute,
} as any)
const ConsoleTeamsRoute = ConsoleTeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => ConsoleRouteRoute,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleAdminIndexRoute = ConsoleAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ConsoleAdminRouteRoute,
} as any)
const ConsoleAdminTenantIdRoute = ConsoleAdminTenantIdRouteImport.update({
  id: '/$tenantId',
  path: '/$tenantId',
  getParentRoute: () => ConsoleAdminRouteRoute,
} as any)
const ConsoleAdminTenantIdIndexRoute =
  ConsoleAdminTenantIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ConsoleAdminTenantIdRoute,
  } as any)
const ConsoleAdminTenantIdInviteRoute =
  ConsoleAdminTenantIdInviteRouteImport.update({
    id: '/invite',
    path: '/invite',
    getParentRoute: () => ConsoleAdminTenantIdRoute,
  } as any)
const ConsoleAdminTenantIdOnboardRoute =
  ConsoleAdminTenantIdOnboardRouteImport.update({
    id: '/onboard',
    path: '/onboard',
    getParentRoute: () => ConsoleAdminTenantIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/console': typeof ConsoleRouteRouteWithChildren
  '/end-shift': typeof EndShiftRoute
  '/report': typeof ReportRoute
  '/timeline': typeof TimelineRoute
  '/console/admin': typeof ConsoleAdminRouteRouteWithChildren
  '/console/calendar': typeof ConsoleCalendarRoute
  '/console/data': typeof ConsoleDataRoute
  '/console/events': typeof ConsoleEventsRoute
  '/console/integrations': typeof ConsoleIntegrationsRoute
  '/console/maintenance': typeof ConsoleMaintenanceRoute
  '/console/rca': typeof ConsoleRcaRoute
  '/console/shifts': typeof ConsoleShiftsRoute
  '/console/teams': typeof ConsoleTeamsRoute
  '/invite/$token': typeof InviteTokenRoute
  '/console/': typeof ConsoleIndexRoute
  '/console/admin/$tenantId': typeof ConsoleAdminTenantIdRouteWithChildren
  '/console/admin/': typeof ConsoleAdminIndexRoute
  '/console/admin/$tenantId/invite': typeof ConsoleAdminTenantIdInviteRoute
  '/console/admin/$tenantId/onboard': typeof ConsoleAdminTenantIdOnboardRoute
  '/console/admin/$tenantId/': typeof ConsoleAdminTenantIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/end-shift': typeof EndShiftRoute
  '/report': typeof ReportRoute
  '/timeline': typeof TimelineRoute
  '/console/calendar': typeof ConsoleCalendarRoute
  '/console/data': typeof ConsoleDataRoute
  '/console/events': typeof ConsoleEventsRoute
  '/console/integrations': typeof ConsoleIntegrationsRoute
  '/console/maintenance': typeof ConsoleMaintenanceRoute
  '/console/rca': typeof ConsoleRcaRoute
  '/console/shifts': typeof ConsoleShiftsRoute
  '/console/teams': typeof ConsoleTeamsRoute
  '/invite/$token': typeof InviteTokenRoute
  '/console': typeof ConsoleIndexRoute
  '/console/admin': typeof ConsoleAdminIndexRoute
  '/console/admin/$tenantId/invite': typeof ConsoleAdminTenantIdInviteRoute
  '/console/admin/$tenantId/onboard': typeof ConsoleAdminTenantIdOnboardRoute
  '/console/admin/$tenantId': typeof ConsoleAdminTenantIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/console': typeof ConsoleRouteRouteWithChildren
  '/end-shift': typeof EndShiftRoute
  '/report': typeof ReportRoute
  '/timeline': typeof TimelineRoute
  '/console/admin': typeof ConsoleAdminRouteRouteWithChildren
  '/console/calendar': typeof ConsoleCalendarRoute
  '/console/data': typeof ConsoleDataRoute
  '/console/events': typeof ConsoleEventsRoute
  '/console/integrations': typeof ConsoleIntegrationsRoute
  '/console/maintenance': typeof ConsoleMaintenanceRoute
  '/console/rca': typeof ConsoleRcaRoute
  '/console/shifts': typeof ConsoleShiftsRoute
  '/console/teams': typeof ConsoleTeamsRoute
  '/invite/$token': typeof InviteTokenRoute
  '/console/': typeof ConsoleIndexRoute
  '/console/admin/$tenantId': typeof ConsoleAdminTenantIdRouteWithChildren
  '/console/admin/': typeof ConsoleAdminIndexRoute
  '/console/admin/$tenantId/invite': typeof ConsoleAdminTenantIdInviteRoute
  '/console/admin/$tenantId/onboard': typeof ConsoleAdminTenantIdOnboardRoute
  '/console/admin/$tenantId/': typeof ConsoleAdminTenantIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/console'
    | '/end-shift'
    | '/report'
    | '/timeline'
    | '/console/admin'
    | '/console/calendar'
    | '/console/data'
    | '/console/events'
    | '/console/integrations'
    | '/console/maintenance'
    | '/console/rca'
    | '/console/shifts'
    | '/console/teams'
    | '/invite/$token'
    | '/console/'
    | '/console/admin/$tenantId'
    | '/console/admin/'
    | '/console/admin/$tenantId/invite'
    | '/console/admin/$tenantId/onboard'
    | '/console/admin/$tenantId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/end-shift'
    | '/report'
    | '/timeline'
    | '/console/calendar'
    | '/console/data'
    | '/console/events'
    | '/console/integrations'
    | '/console/maintenance'
    | '/console/rca'
    | '/console/shifts'
    | '/console/teams'
    | '/invite/$token'
    | '/console'
    | '/console/admin'
    | '/console/admin/$tenantId/invite'
    | '/console/admin/$tenantId/onboard'
    | '/console/admin/$tenantId'
  id:
    | '__root__'
    | '/'
    | '/console'
    | '/end-shift'
    | '/report'
    | '/timeline'
    | '/console/admin'
    | '/console/calendar'
    | '/console/data'
    | '/console/events'
    | '/console/integrations'
    | '/console/maintenance'
    | '/console/rca'
    | '/console/shifts'
    | '/console/teams'
    | '/invite/$token'
    | '/console/'
    | '/console/admin/$tenantId'
    | '/console/admin/'
    | '/console/admin/$tenantId/invite'
    | '/console/admin/$tenantId/onboard'
    | '/console/admin/$tenantId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConsoleRouteRoute: typeof ConsoleRouteRouteWithChildren
  EndShiftRoute: typeof EndShiftRoute
  ReportRoute: typeof ReportRoute
  TimelineRoute: typeof TimelineRoute
  InviteTokenRoute: typeof InviteTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console': {
      id: '/console'
      path: '/console'
      fullPath: '/console'
      preLoaderRoute: typeof ConsoleRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/end-shift': {
      id: '/end-shift'
      path: '/end-shift'
      fullPath: '/end-shift'
      preLoaderRoute: typeof EndShiftRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timeline': {
      id: '/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof TimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console/': {
      id: '/console/'
      path: '/'
      fullPath: '/console/'
      preLoaderRoute: typeof ConsoleIndexRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/console/admin': {
      id: '/console/admin'
      path: '/admin'
      fullPath: '/console/admin'
      preLoaderRoute: typeof ConsoleAdminRouteRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/console/calendar': {
      id: '/console/calendar'
      path: '/calendar'
      fullPath: '/console/calendar'
      preLoaderRoute: typeof ConsoleCalendarRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/console/data': {
      id: '/console/data'
      path: '/data'
      fullPath: '/console/data'
      preLoaderRoute: typeof ConsoleDataRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/console/events': {
      id: '/console/events'
      path: '/events'
      fullPath: '/console/events'
      preLoaderRoute: typeof ConsoleEventsRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/console/integrations': {
      id: '/console/integrations'
      path: '/integrations'
      fullPath: '/console/integrations'
      preLoaderRoute: typeof ConsoleIntegrationsRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/console/maintenance': {
      id: '/console/maintenance'
      path: '/maintenance'
      fullPath: '/console/maintenance'
      preLoaderRoute: typeof ConsoleMaintenanceRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/console/rca': {
      id: '/console/rca'
      path: '/rca'
      fullPath: '/console/rca'
      preLoaderRoute: typeof ConsoleRcaRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/console/shifts': {
      id: '/console/shifts'
      path: '/shifts'
      fullPath: '/console/shifts'
      preLoaderRoute: typeof ConsoleShiftsRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/console/teams': {
      id: '/console/teams'
      path: '/teams'
      fullPath: '/console/teams'
      preLoaderRoute: typeof ConsoleTeamsRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console/admin/': {
      id: '/console/admin/'
      path: '/'
      fullPath: '/console/admin/'
      preLoaderRoute: typeof ConsoleAdminIndexRouteImport
      parentRoute: typeof ConsoleAdminRouteRoute
    }
    '/console/admin/$tenantId': {
      id: '/console/admin/$tenantId'
      path: '/$tenantId'
      fullPath: '/console/admin/$tenantId'
      preLoaderRoute: typeof ConsoleAdminTenantIdRouteImport
      parentRoute: typeof ConsoleAdminRouteRoute
    }
    '/console/admin/$tenantId/': {
      id: '/console/admin/$tenantId/'
      path: '/'
      fullPath: '/console/admin/$tenantId/'
      preLoaderRoute: typeof ConsoleAdminTenantIdIndexRouteImport
      parentRoute: typeof ConsoleAdminTenantIdRoute
    }
    '/console/admin/$tenantId/invite': {
      id: '/console/admin/$tenantId/invite'
      path: '/invite'
      fullPath: '/console/admin/$tenantId/invite'
      preLoaderRoute: typeof ConsoleAdminTenantIdInviteRouteImport
      parentRoute: typeof ConsoleAdminTenantIdRoute
    }
    '/console/admin/$tenantId/onboard': {
      id: '/console/admin/$tenantId/onboard'
      path: '/onboard'
      fullPath: '/console/admin/$tenantId/onboard'
      preLoaderRoute: typeof ConsoleAdminTenantIdOnboardRouteImport
      parentRoute: typeof ConsoleAdminTenantIdRoute
    }
  }
}

interface ConsoleAdminTenantIdRouteChildren {
  ConsoleAdminTenantIdInviteRoute: typeof ConsoleAdminTenantIdInviteRoute
  ConsoleAdminTenantIdOnboardRoute: typeof ConsoleAdminTenantIdOnboardRoute
  ConsoleAdminTenantIdIndexRoute: typeof ConsoleAdminTenantIdIndexRoute
}

const ConsoleAdminTenantIdRouteChildren: ConsoleAdminTenantIdRouteChildren = {
  ConsoleAdminTenantIdInviteRoute: ConsoleAdminTenantIdInviteRoute,
  ConsoleAdminTenantIdOnboardRoute: ConsoleAdminTenantIdOnboardRoute,
  ConsoleAdminTenantIdIndexRoute: ConsoleAdminTenantIdIndexRoute,
}

const ConsoleAdminTenantIdRouteWithChildren =
  ConsoleAdminTenantIdRoute._addFileChildren(ConsoleAdminTenantIdRouteChildren)

interface ConsoleAdminRouteRouteChildren {
  ConsoleAdminTenantIdRoute: typeof ConsoleAdminTenantIdRouteWithChildren
  ConsoleAdminIndexRoute: typeof ConsoleAdminIndexRoute
}

const ConsoleAdminRouteRouteChildren: ConsoleAdminRouteRouteChildren = {
  ConsoleAdminTenantIdRoute: ConsoleAdminTenantIdRouteWithChildren,
  ConsoleAdminIndexRoute: ConsoleAdminIndexRoute,
}

const ConsoleAdminRouteRouteWithChildren =
  ConsoleAdminRouteRoute._addFileChildren(ConsoleAdminRouteRouteChildren)

interface ConsoleRouteRouteChildren {
  ConsoleAdminRouteRoute: typeof ConsoleAdminRouteRouteWithChildren
  ConsoleCalendarRoute: typeof ConsoleCalendarRoute
  ConsoleDataRoute: typeof ConsoleDataRoute
  ConsoleEventsRoute: typeof ConsoleEventsRoute
  ConsoleIntegrationsRoute: typeof ConsoleIntegrationsRoute
  ConsoleMaintenanceRoute: typeof ConsoleMaintenanceRoute
  ConsoleRcaRoute: typeof ConsoleRcaRoute
  ConsoleShiftsRoute: typeof ConsoleShiftsRoute
  ConsoleTeamsRoute: typeof ConsoleTeamsRoute
  ConsoleIndexRoute: typeof ConsoleIndexRoute
}

const ConsoleRouteRouteChildren: ConsoleRouteRouteChildren = {
  ConsoleAdminRouteRoute: ConsoleAdminRouteRouteWithChildren,
  ConsoleCalendarRoute: ConsoleCalendarRoute,
  ConsoleDataRoute: ConsoleDataRoute,
  ConsoleEventsRoute: ConsoleEventsRoute,
  ConsoleIntegrationsRoute: ConsoleIntegrationsRoute,
  ConsoleMaintenanceRoute: ConsoleMaintenanceRoute,
  ConsoleRcaRoute: ConsoleRcaRoute,
  ConsoleShiftsRoute: ConsoleShiftsRoute,
  ConsoleTeamsRoute: ConsoleTeamsRoute,
  ConsoleIndexRoute: ConsoleIndexRoute,
}

const ConsoleRouteRouteWithChildren = ConsoleRouteRoute._addFileChildren(
  ConsoleRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConsoleRouteRoute: ConsoleRouteRouteWithChildren,
  EndShiftRoute: EndShiftRoute,
  ReportRoute: ReportRoute,
  TimelineRoute: TimelineRoute,
  InviteTokenRoute: InviteTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
